name: my_egabat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.0
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.1.0
  flutter_icons_null_safety: ^1.1.0
  get: 4.6.5
  http: ^1.1.0
  image_picker: ^1.0.1
  introduction_screen: ^3.1.11
  libphonenumber: ^2.0.2
  lottie: ^2.4.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
