name: my_egabat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.1.0
  get: 4.6.5
  introduction_screen: ^3.1.11
  lottie: ^2.4.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
